### ISSUE TITLE
Combination of gotoxy, and kbhit() not working when there is a print(...,end=)

### ISSUE THREAD

**Issue by JuriTuuti** [Solomoriah/WConio2#2]
(Wrong text on header, unable to edit or delete... Sorry.)
gotoxy() does not work, if print function without line ending has been used before:

gotoxy(5,5)
print('one',end='')
gotoxy(6,6)
print('two')
gotoxy(7,7)
print('three')

prints:
 onetwo
  three

**Comment by Solomoriah** [comment]
You should not try to combine standard IO with WConio, ever.  In other words, this is not a bug, this is undefined behavior.
